apiVersion: v1
kind: Service
metadata:
  name: guestbook-advanced
  namespace: guestbook-advanced-dev
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: guestbook-advanced
