# This is a sample analysis template that uses the PokeAPI to
# check the base experience of a Pokemon is under threshold.
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pokemon-xp
  namespace: kargo-advanced
spec:
  args:
  - name: pokemon
  metrics:
  - name: pokemon-xp
    interval: 5s
    count: 5
    successCondition: result < 200
    failureLimit: 3
    provider:
      web:
        url: https://pokeapi.co/api/v2/pokemon/{{args.pokemon}}
        jsonPath: "{$.base_experience}"

--- 

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: kargo-advanced
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://frontend.gap-system.svc.cluster.local:9090
        # timeout is expressed in seconds
        timeout: 40
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
          ))
