apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook-advanced
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: guestbook-advanced-*
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/icarusdes/kargo-advanced.git
