apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-advanced
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-advanced
  template:
    metadata:
      labels:
        app: guestbook-advanced
    spec:
      containers:
      - image: us-east4-docker.pkg.dev/sap-ems-gap-sandbox/ghcr/icarusdes/guestbook-advanced:latest
        name: guestbook-advanced
        ports:
        - name: http
          containerPort: 3000
